version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kp_bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - MINI_APP_URL=${MINI_APP_URL}
    volumes:
      - ./logs:/app/logs  # Для логов (опционально)
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
